import java.util.HashMap;
import java.util.Map;

/**
 * @author Jacob Ho
 */
public class MinusMap extends HashMap<String, Map<String, String>> {
    public MinusMap() {
        Map<String, String> map0 = new HashMap<>();
        map0.put("0", "0");
        map0.put("1", "-1");
        map0.put("2", "-2");
        map0.put("3", "-3");
        map0.put("4", "-4");
        map0.put("5", "-5");
        map0.put("6", "-6");
        map0.put("7", "-7");
        map0.put("8", "-8");
        map0.put("9", "-9");
        put("0", map0);
        Map<String, String> map1 = new HashMap<>();
        map1.put("0", "1");
        map1.put("1", "0");
        map1.put("2", "-1");
        map1.put("3", "-2");
        map1.put("4", "-3");
        map1.put("5", "-4");
        map1.put("6", "-5");
        map1.put("7", "-6");
        map1.put("8", "-7");
        map1.put("9", "-8");
        put("1", map1);
        Map<String, String> map2 = new HashMap<>();
        map2.put("0", "2");
        map2.put("1", "1");
        map2.put("2", "0");
        map2.put("3", "-1");
        map2.put("4", "-2");
        map2.put("5", "-3");
        map2.put("6", "-4");
        map2.put("7", "-5");
        map2.put("8", "-6");
        map2.put("9", "-7");
        put("2", map2);
        Map<String, String> map3 = new HashMap<>();
        map3.put("0", "3");
        map3.put("1", "2");
        map3.put("2", "1");
        map3.put("3", "0");
        map3.put("4", "-1");
        map3.put("5", "-2");
        map3.put("6", "-3");
        map3.put("7", "-4");
        map3.put("8", "-5");
        map3.put("9", "-6");
        put("3", map3);
        Map<String, String> map4 = new HashMap<>();
        map4.put("0", "4");
        map4.put("1", "3");
        map4.put("2", "2");
        map4.put("3", "1");
        map4.put("4", "0");
        map4.put("5", "-1");
        map4.put("6", "-2");
        map4.put("7", "-3");
        map4.put("8", "-4");
        map4.put("9", "-5");
        put("4", map4);
        Map<String, String> map5 = new HashMap<>();
        map5.put("0", "5");
        map5.put("1", "4");
        map5.put("2", "3");
        map5.put("3", "2");
        map5.put("4", "1");
        map5.put("5", "0");
        map5.put("6", "-1");
        map5.put("7", "-2");
        map5.put("8", "-3");
        map5.put("9", "-4");
        put("5", map5);
        Map<String, String> map6 = new HashMap<>();
        map6.put("0", "6");
        map6.put("1", "5");
        map6.put("2", "4");
        map6.put("3", "3");
        map6.put("4", "2");
        map6.put("5", "1");
        map6.put("6", "0");
        map6.put("7", "-1");
        map6.put("8", "-2");
        map6.put("9", "-3");
        put("6", map6);
        Map<String, String> map7 = new HashMap<>();
        map7.put("0", "7");
        map7.put("1", "6");
        map7.put("2", "5");
        map7.put("3", "4");
        map7.put("4", "3");
        map7.put("5", "2");
        map7.put("6", "1");
        map7.put("7", "0");
        map7.put("8", "-1");
        map7.put("9", "-2");
        put("7", map7);
        Map<String, String> map8 = new HashMap<>();
        map8.put("0", "8");
        map8.put("1", "7");
        map8.put("2", "6");
        map8.put("3", "5");
        map8.put("4", "4");
        map8.put("5", "3");
        map8.put("6", "2");
        map8.put("7", "1");
        map8.put("8", "0");
        map8.put("9", "-1");
        put("8", map8);
        Map<String, String> map9 = new HashMap<>();
        map9.put("0", "9");
        map9.put("1", "8");
        map9.put("2", "7");
        map9.put("3", "6");
        map9.put("4", "5");
        map9.put("5", "4");
        map9.put("6", "3");
        map9.put("7", "2");
        map9.put("8", "1");
        map9.put("9", "0");
        put("9", map9);
        Map<String, String> map10 = new HashMap<>();
        map10.put("0", "10");
        map10.put("1", "9");
        map10.put("2", "8");
        map10.put("3", "7");
        map10.put("4", "6");
        map10.put("5", "5");
        map10.put("6", "4");
        map10.put("7", "3");
        map10.put("8", "2");
        map10.put("9", "1");
        put("10", map10);
    }
}
