import java.util.HashMap;
import java.util.Map;

/**
 * @author Jacob Ho
 */
public class SumMap extends HashMap<String, Map<String, String>> {
    public SumMap() {
        Map<String, String> map0 = new HashMap<>();
        map0.put("0", "0");
        map0.put("1", "1");
        map0.put("2", "2");
        map0.put("3", "3");
        map0.put("4", "4");
        map0.put("5", "5");
        map0.put("6", "6");
        map0.put("7", "7");
        map0.put("8", "8");
        map0.put("9", "9");
        put("0", map0);
        Map<String, String> map1 = new HashMap<>();
        map1.put("0", "1");
        map1.put("1", "2");
        map1.put("2", "3");
        map1.put("3", "4");
        map1.put("4", "5");
        map1.put("5", "6");
        map1.put("6", "7");
        map1.put("7", "8");
        map1.put("8", "9");
        map1.put("9", "10");
        put("1", map1);
        Map<String, String> map2 = new HashMap<>();
        map2.put("0", "2");
        map2.put("1", "3");
        map2.put("2", "4");
        map2.put("3", "5");
        map2.put("4", "6");
        map2.put("5", "7");
        map2.put("6", "8");
        map2.put("7", "9");
        map2.put("8", "10");
        map2.put("9", "11");
        put("2", map2);
        Map<String, String> map3 = new HashMap<>();
        map3.put("0", "3");
        map3.put("1", "4");
        map3.put("2", "5");
        map3.put("3", "6");
        map3.put("4", "7");
        map3.put("5", "8");
        map3.put("6", "9");
        map3.put("7", "10");
        map3.put("8", "11");
        map3.put("9", "12");
        put("3", map3);
        Map<String, String> map4 = new HashMap<>();
        map4.put("0", "4");
        map4.put("1", "5");
        map4.put("2", "6");
        map4.put("3", "7");
        map4.put("4", "8");
        map4.put("5", "9");
        map4.put("6", "10");
        map4.put("7", "11");
        map4.put("8", "12");
        map4.put("9", "13");
        put("4", map4);
        Map<String, String> map5 = new HashMap<>();
        map5.put("0", "5");
        map5.put("1", "6");
        map5.put("2", "7");
        map5.put("3", "8");
        map5.put("4", "9");
        map5.put("5", "10");
        map5.put("6", "11");
        map5.put("7", "12");
        map5.put("8", "13");
        map5.put("9", "14");
        put("5", map5);
        Map<String, String> map6 = new HashMap<>();
        map6.put("0", "6");
        map6.put("1", "7");
        map6.put("2", "8");
        map6.put("3", "9");
        map6.put("4", "10");
        map6.put("5", "11");
        map6.put("6", "12");
        map6.put("7", "13");
        map6.put("8", "14");
        map6.put("9", "15");
        put("6", map6);
        Map<String, String> map7 = new HashMap<>();
        map7.put("0", "7");
        map7.put("1", "8");
        map7.put("2", "9");
        map7.put("3", "10");
        map7.put("4", "11");
        map7.put("5", "12");
        map7.put("6", "13");
        map7.put("7", "14");
        map7.put("8", "15");
        map7.put("9", "16");
        put("7", map7);
        Map<String, String> map8 = new HashMap<>();
        map8.put("0", "8");
        map8.put("1", "9");
        map8.put("2", "10");
        map8.put("3", "11");
        map8.put("4", "12");
        map8.put("5", "13");
        map8.put("6", "14");
        map8.put("7", "15");
        map8.put("8", "16");
        map8.put("9", "17");
        put("8", map8);
        Map<String, String> map9 = new HashMap<>();
        map9.put("0", "9");
        map9.put("1", "10");
        map9.put("2", "11");
        map9.put("3", "12");
        map9.put("4", "13");
        map9.put("5", "14");
        map9.put("6", "15");
        map9.put("7", "16");
        map9.put("8", "17");
        map9.put("9", "18");
        put("9", map9);
    }
}
